version: "3.9"

services:
  frontend:
    build: ./frontend/
    ports:
      - "4000:4000"

  backend:
    build: ./backend/
    ports:
      - "1337:1337"
    environment:
      DB_PROVIDER: postgres
      NODE_ENV: production
      URL: http://localhost:1337
      DATABASE_HOST: db
      ADMIN_JWT_SECRET: ErhxCk10YqNCImwodl5Ml/Maqnw46oTyLjr+9Na4bjmJSLVWnCS90BJRAAkLsspj98caylAJgikBO9ZS0jEiOQ==)
      DATABASE_PASSWORD: mypassword
      SENDGRID_API_KEY: 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
    
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: mypassword
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data